# renew_before_expiry = 30 days
version = 2.11.0
archive_dir = /etc/letsencrypt/archive/www.lxziyuan.site
cert = /etc/letsencrypt/live/www.lxziyuan.site/cert.pem
privkey = /etc/letsencrypt/live/www.lxziyuan.site/privkey.pem
chain = /etc/letsencrypt/live/www.lxziyuan.site/chain.pem
fullchain = /etc/letsencrypt/live/www.lxziyuan.site/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = aa7733e6c68bb46c3392262fbd754539
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
www.lxziyuan.site = /var/www/certbot
